export type RootStackParamList = {
    Welcome: undefined;
    Login: undefined;
    Register: undefined;
    Home: undefined;
    WallpaperDetail: { wallpaperId: number };
    CategoryDetail: { categoryId: number };
    Subscription: undefined;
    Profile: undefined;
    Settings: undefined;
    Premium: undefined;
    Favorites: undefined;
    PasswordChange: undefined;
    ProfileUpdate: undefined;
    CleanScreen: undefined;
    PixabayScreen: undefined;
    Payment: undefined;
    Faq: undefined;
    WallpaperHome: undefined;
};